#                ██████████                        
#            ████          ████              _ (`-.  ('-. .-.   ('-.         .-') _  .-') _                _   .-')             
#          ██                  ██           ( (OO  )( OO )  /  ( OO ).-.    ( OO ) )(  OO) )              ( '.( OO )_           
#        ██                      ██        _.`     \,--. ,--.  / . --. /,--./ ,--,' /     '._  .-'),-----. ,--.   ,--.)         
#      ██                          ██     (__...--''|  | |  |  | \-.  \ |   \ |  |\ |'--...__)( OO'  .-.  '|   `.'   |          
#    ██                              ██    |  /  | ||   .|  |.-'-'  |  ||    \|  | )'--.  .--'/   |  | |  ||         |          
#    ██                              ██    |  |_.' ||       | \| |_.'  ||  .     |/    |  |   \_) |  |\|  ||  |'.'|  |          
#  ██        ████        ████          ██  |  .___.'|  .-.  |  |  .-.  ||  |\    |     |  |     \ |  | |  ||  |   |  |          
#  ██        ██            ██          ██  |  |     |  | |  |  |  | |  ||  | \   |     |  |      `'  '-'  '|  |   |  |          
#  ██        ████        ████          ██  `--'     `--' `--'  `--' `--'`--'  `--'     `--'        `-----' `--'   `--'          
#  ██    ░░░░                ░░░░      ██          
#  ██            ████████              ██          
#  ██  ██████              ██████      ██          
#  ██        ██          ██            ██          
#  ██        ██          ██            ██          
#  ██  ██████              ██████        ██    ██  
#  ██                                      ████  ██
#    ██                                          ██
#    ██                                          ██
#      ██                                      ██  
#        ██                                    ██  
#          ██                              ████    
#            ████                      ████        
#                ██████████████████████            


# Version of this config. Please do not change.
configVersion: 8

# Where do you want phantom to run?
serverInfo:
    host: 0.0.0.0
    port: 25565

# What should the broadcast sent to players look like (number from one to three)?
Style: 2
# Option One:
#                          Upper Message ꖦ
# ████ Lower Message     ⡏ Hover Message ⢹
# ████                   ⣇               ⣸

# Option Two:
#                                    0/0 ꔖ
# ████ Lower Message     ⡏ Hover Message ⢹
# ████                   ⣇               ⣸

# Option Three:
#                                    0/1 ꔖ
# ████ Lower Message     ⡏ Hover Message ⢹
# ████                   ⣇               ⣸


Content:
    # What will the server's MOTD show as? Max 2 lines.
    lowerMessage: |-
      &8[&7&lPhantom&8]
      &f&oThis server is just a broadcast!
    # Text shown above the server
    upperMessage: '&fThis msg appears above the server!'
    # This text will appear when someone hovers over the server's status indicator 
    hoverMessage: |-
      &7[&f&lPhantom&7]
      &bThis is some example text
      &3It can be as long and wide
      &3as you want. The Only 
      &3limitation is the size of
      &3the screen.
    # What text is sent to users who try to connect to the server? (no coloring accepted)
    kickMessage: |-
      Players will be kicked with 
      this message!
    # Where can we find a 64x64 pixel png image?
    imagePath: 'server-icon.png'
    # Text shown above the server (Max 29 Chars.)
    

Logging:
    # Append all console messages to console.log
    storeMessages: false
    # List all players who have joined in players.log
    storeUsers: true
    

debug: false
